### ISSUE TITLE
Which areas of the API are being covered?

### ISSUE THREAD

**Issue by anissen** [kevinresol/GoogleApi#1]
_This issue is intended purely for clarification for the purpose of this repository._

The Google Games API is big and spanning a lot of different areas, e.g. leaderboards, achievements, save games, logging, real-time multiplayer, turn-based multiplayer etc.. Which parts will this repository be covering?

I'm asking because I'm especially interested in the [turn-based multiplayer](https://developers.google.com/games/services/android/turnbasedMultiplayer) part and would love to see that being covered :)

**Comment by kevinresol** [comment]
Theoretically, the whole REST API _could be_ covered. Because this repo is mainly a wrapper of the REST API. https://developers.google.com/games/services/web/api/index
The native extension part mainly covers the authentication/authorization procedures in native ways.

**Comment by anissen** [comment]
That sounds great. One thing that the REST API cannot cover, however, is the notification system (e.g. "You have been invited to play a game", "It's your turn", etc.)...
